### ISSUE TITLE
Share without the dialog?

### ISSUE THREAD

**Issue by vinu123** [doefler/react-native-social-share#10]
I was wondering if there's any way to implement social share without the dialog. Could I somehow just pass the parameters and perform share?

**Comment by doefler** [comment]
Hey @vinu123 you could call the facebook graph api directly

Here is an example 
(Copied from https://developers.facebook.com/docs/ios/graph#posting)
``` objc
if ([[FBSDKAccessToken currentAccessToken] hasGranted:@"publish_actions"]) {
  [[[FBSDKGraphRequest alloc]
    initWithGraphPath:@"me/feed"
                     parameters: @{ @"message" : @"hello world"}
               HTTPMethod:@"POST"]
  startWithCompletionHandler:^(FBSDKGraphRequestConnection *connection, id result, NSError *error) {
    if (!error) {
      NSLog(@"Post id:%@", result[@"id"]);
    }
  }];
}

```

Hope this helps :smile:

**Comment by vinu123** [comment]
I feel embarrassed to admit that I dont know Objective C. Would you know how to achieve this using an alternate way? Like in JavaScript?

**Comment by doefler** [comment]
No problem @vinu123 :smile: 

Yes you would easily be able to achieve something like this with JavaScript
https://developers.facebook.com/docs/javascript/examples#graphapi

Lets assume it is on a website you first need permissions to actually publish, if you already have their permission, you can ignore this

``` HTML
<script>
// Only works after `FB.init` is called
function myFacebookLogin() {
  FB.login(function(){}, {scope: 'publish_actions'});
}
</script>
<button onclick="myFacebookLogin()">Login with Facebook</button>
```

After getting their permission and have them succesfully logged in you can publish to their feed in the background with this script

``` JavaScript
FB.login(function(){
  // Note: The call will only work if you accept the permission request
  FB.api('/me/feed', 'post', {message: 'Hello, world!'});
}, {scope: 'publish_actions'});
```

**Comment by vinu123** [comment]
but FB object only becomes available when you have sdk.js included which may very well work for the web but I am afraid it might not work when you are running your app on your device. Please correct me if I am wrong.

**Comment by doefler** [comment]
You can just use some http library to cURL the graph api
If you are using React Native you can use one of the libraries for connecting to facebook
Login
https://github.com/facebook/react-native-fbsdk#login-button
Publish using graph api (just need to customize the code a bit)
https://github.com/facebook/react-native-fbsdk#graph-requests

Alternative login
https://github.com/magus/react-native-facebook-login

**Comment by vinu123** [comment]
Thanks so much @doefler

**Comment by doefler** [comment]
You are very welcome @vinu123 :+1: 
I am happy to help
