### ISSUE TITLE
drop peer dependencies

### ISSUE THREAD

**Issue by chirag04** [doefler/react-native-social-share#11]
Can you drop peer dependency on react-native in package.json and let the host project dictate which react-native version to use?

Social share is not using anything specific to any react-native version. It is safe to remove peer deps i think.

**Comment by doefler** [comment]
I think you are right, it should not need anything specific!

I just removed the peer dependency :+1:

**Comment by doefler** [comment]
Do you think I should make an update to version no + npm

**Comment by chirag04** [comment]
Thanks. Yeah version bump is needed. maybe just call it 1.0.0 since it is stable now?

**Comment by doefler** [comment]
Just did a "minor" version bump :+1:

**Comment by chirag04** [comment]
cool. thanks :+1:

**Comment by chirag04** [comment]
on a side note: do you have plans for android support?

**Comment by doefler** [comment]
Nope no plans at the moment
