### ISSUE TITLE
Post a photo from app

### ISSUE THREAD

**Issue by myusuf3** [doefler/react-native-social-share#12]
Is there a way for this plugin to post image from camera roll through this.

**Comment by doefler** [comment]
I am actually not sure if that can be done this way
You can look at 
https://facebook.github.io/react-native/docs/cameraroll.html

The imagelink parameter can take an image from an external URL, but maybe you can load a local image as well if you get the local address.

**Comment by myusuf3** [comment]
I managed to tweak it to load local image. That is totally possible.

**Comment by doefler** [comment]
Cool :+1: 
Did you tweak the bridge file or did you do it in js?
Do you have a code sample, would be cool to know how you did. I could also add it to the documentation :smile:

**Comment by myusuf3** [comment]
All I needed to do was to edit the objective c code to load image asset from disk coerce it to UIImage then set it on the field.

**Comment by doefler** [comment]
Ahh I see :smile:

**Comment by myusuf3** [comment]
I have a fork here that made the change for the facebook sharing. https://github.com/gyroscope-innovations/react-native-social-share isn't cleanest thing ever since I was working towards getting release out.
