### ISSUE TITLE
default facebook text message

### ISSUE THREAD

**Issue by FaridSafi** [doefler/react-native-social-share#14]
Hello, thank you @doefler for this component

I tested to share using my device and it works properly with Twitter, but I can not set a default text message with Facebook.

```js
                KDSocialShare.shareOnFacebook({
                    'text':'Download the app',
                    'link':'http://google.com/',
                  },
                  (results) => {
                    console.log(results);
                  }
                );
```

![img_0752](https://cloud.githubusercontent.com/assets/388375/12081434/0825890e-b279-11e5-93e1-fab36f327c04.PNG)

"Download the app" doesn't appear on Facebook share dialog

React-Native 0.17.0
iOS 9.2
nodejs v5.1.1
XCode 7.2

**Comment by doefler** [comment]
Hey @FaridSafi, You are welcome!
I am sad you have that issue too.
Several have had that problem, including myself.
I don't know how to fix it properly, sorry!
:smile:
