### ISSUE TITLE
404 => JSON value '<null>' of type NSNull cannot be converted to NSString

### ISSUE THREAD

**Issue by udfalkso** [doefler/react-native-social-share#15]
I believe this happens if you attempt to share a link that leads to a 404, but I'm not 100% sure.  Ideally this situation would be protected against.  Thanks for the great module!

![slack for ios upload-1 png](https://cloud.githubusercontent.com/assets/2029383/12799913/91b95734-ca9f-11e5-8f06-01a814500778.jpeg)

**Comment by doefler** [comment]
Hi @udfalkso :smile: 
Thank you for letting me know about the problem.
As you say that actually should be prevented inside Obj-C so that the javascript receives a nice error message.
I am happy you like the module!

**Comment by udfalkso** [comment]
https://github.com/doefler/react-native-social-share/pull/16

**Comment by doefler** [comment]
I merged the changes. Will close this issue then :+1:
