### ISSUE TITLE
Exception '-[UIKeyboardTaskQueue waitUntilAllTasksAreFinished] may only be called from the main thread

### ISSUE THREAD

**Issue by magus** [doefler/react-native-social-share#20]
```
CrashlyticsReactLogFunction_block_invoke line 203 $ REACT LOG: 2016-05-06 19:32:46.904 [fatal][tid:com.facebook.React.KDSocialShareQueue] Exception '-[UIKeyboardTaskQueue waitUntilAllTasksAreFinished] may only be called from the main thread.' was thrown while invoking shareOnFacebook on target KDSocialShare with params
```

Seems like there is an intermittent issue when calling these methods. If the method is run off the main queue there is an error thrown. Adding 

```
- (dispatch_queue_t)methodQueue
{
  return dispatch_get_main_queue();
}
```

...to `KDSocialShare.m` seems to have resolved this intermittent crash. It's a small fix I can create a PR but not sure I fully understand the issue since the rest seems to be closed source.

**Comment by doefler** [comment]
Hey @magus 
Are you running it off the main thread?
As far as I know all UI related task should be run on the main thread. 
In this case the method presents a popup along with the keyboard, both are UI elements, so I guess it makes sense that it throws an error?!

**Comment by magus** [comment]
So I think we should add that snippet above to ensure it runs on the main thread. It resolves the issue entirely. Want a PR?
