### ISSUE TITLE
Libraries miss

### ISSUE THREAD

**Issue by chaochaohao** [doefler/react-native-social-share#22]
Hello, i was according to document : npm install react-native-social-share --save, but miss Libraries file.
![image](https://cloud.githubusercontent.com/assets/10116477/15797440/d16c9afc-2a4a-11e6-8307-9f619eb9fe7a.png), How can i do? Thanks!

**Comment by doefler** [comment]
Hi @chaochaohao 
You need to add the files to your Libraries before you can see them. They are located in the node_modules folder in your project.
> 2: In XCode, in the project navigator right click Libraries ➜ Add Files to [your project's name]
> 3: Go to node_modules ➜ react-native-social-share➜ iOS and add KDSocialShare.h and KDSocialShare.m

Hope this helps you
