### ISSUE TITLE
Is not visible inside <Modal>

### ISSUE THREAD

**Issue by darrenfurr** [doefler/react-native-social-share#23]
I'm trying to use this component inside a modal, but it does not appear on top of the modal. When I move the buttons to the rootview it works fine.

Thanks for any help with this.

**Comment by doefler** [comment]
Hi @darrenfurr 
I actually don't know why this might happen, but my best guess is that both views are modals and therefore conflicts.
Could you close the modal first and then share?
1. So click button in modal
2. Send event to parent view (tell it to do step 3 and 4)
3. Close modal
4. Open share modal
...

Hope it makes sense 😄

**Comment by darrenfurr** [comment]
It does make sense. Our view was getting complex, so I implemented navigator instead.  Thanks for the response.

**Comment by doefler** [comment]
@darrenfurr: ahh I see, sounds like a good idea 👍 
No problem, happy coding 😄
