### ISSUE TITLE
Facebook 'text' property not working with FB version 59.0.0.51.142

### ISSUE THREAD

**Issue by darrenfurr** [doefler/react-native-social-share#24]
I'm using KDSocialShare in my app, but unfortunately, it appears that Facebook may have changed how it interfaces with SLComposeViewController?  

The Twitter integration is still working correctly & the message loads correctly for Facebook in the Simulator. 

Any help would be appreciated.
-Darren

**Comment by doefler** [comment]
Hey Darren @darrenfurr 

I am not sure what that would be.
Can you check that you are logged into Facebook in the iPhone settings?

**Comment by darrenfurr** [comment]
Yeah - I am. I think it is the same issue that others have reported. I may throw some logging to the console in xCode to confirm that the text is coming in. I'll let you know what I find.

**Comment by doefler** [comment]
What version of react-native-social-share are you running?
There has been made some changes to the obj-c files that should fix some issues with the Facebook share modal.
Trying doing a npm update on the module

**Comment by darrenfurr** [comment]
I'm running 0.8.0. I also did an NSLog & of course it comes through in the Simulator (but - it's always worked in the simulator!).

Looks like as of iOS 8 - Facebook is ignoring setInitialText on the SLComposeViewController. According to FB - this is "by design & we should see the Privacy Policy"
https://developers.facebook.com/bugs/962985360399542

Apparently - we need to use the FB SDK. 👎

**Comment by doefler** [comment]
👎 
Sorry about that!
Hope You find an alternative solution with the FB SDK.

**Comment by darrenfurr** [comment]
Well - now you know for anyone else who reports it.  Apparently, if you uninstall the FB app - it works. 

This looks promising for a react-native facebook sdk option:
https://github.com/facebook/react-native-fbsdk

**Comment by doefler** [comment]
Thanks mate 😄

**Comment by iChriiss** [comment]
Not sure if this helps, but this issue seems to occur only if the FB App is installed on the device, hence why it does not occur in the simulator!
