### ISSUE TITLE
Question: Success popup for Facebook post

### ISSUE THREAD

**Issue by dwilt** [doefler/react-native-social-share#25]
The popup that shows when you make a successful Facebook post:

![image](https://cloud.githubusercontent.com/assets/1065539/17599306/4dbf58f4-5fb3-11e6-8b78-9fda74dd39bb.png)

Couple questions:

1. Why doesn't it do this when you post to Twitter?
2. I'd like to use this sort of animation/confirmation for other things in the app to keep a consistent UX. Is this a separate component and if so, do you know how I could use it? At the very least, I'd like to disable it so I could create a custom one for all of the features in my app. Thanks!

**Comment by doefler** [comment]
Hi @dwilt 

1.  Q: Why doesn't it do this when you post to Twitter?

 A: I think the popup happens within Facebooks app or their posting module.

2. Q: I'd like to use this sort of animation/confirmation for other things in the app to keep a consistent UX. Is this a separate component and if so, do you know how I could use it? At the very least, I'd like to disable it so I could create a custom one for all of the features in my app.

 A: I didn't implement this feature, as mentioned before, I think it is something happening in Facebook's app. Therefore I don't know if you can disable it.
Maybe it is a new feature you can turn off by passing some option to the native module `SLComposeViewController `.
If you find out, please let me know.
