### ISSUE TITLE
Path name for Assets library?

### ISSUE THREAD

**Issue by divye01** [doefler/react-native-social-share#27]
Can I assign the direct path of assets-library, for example: assets-library://asset/asset.JPG?id=C4E468CC-3B82-4822-8FEE-BA1C1DC47B4B&ext=JPG, or do I have to assign the filename from there?

**Comment by divye01** [comment]
We can add a filePath by editing the following line of KBDSocialShare.m
` UIImage *image = [UIImage imageWithData:[NSData dataWithContentsOfURL:[NSURL URLWithPath:imagelink]]];
` to 
`    UIImage *image = [UIImage imageWithData:[NSData dataWithContentsOfURL:[NSURL **fileURLWithPath:imagelink**]]];
`

**Comment by doefler** [comment]
Hi @divye01 
I am not sure what the difference between what you are trying to achieve and the `image` parameter?

Using ´imageLink` gives you a publicly hosted image and `image` lets you use an image in the app.

**Comment by divye01** [comment]
Yes, but if you want to give an image link stored in the app itself the image parameter doesn't work. Since it takes the image from assets library. However, you can provide an in-app link to an image by using `fileURLWithPath` for imagelink.
