### ISSUE TITLE
Tweet callback says `success` but tweet failed to send

### ISSUE THREAD

**Issue by dwilt** [doefler/react-native-social-share#28]
If you have the Twitter app installed but are not logged in and try and use the `KDSocialShare.tweet` function it says it was a `success` but when I go into Twitter to check my feed I'm prompted immediately that the tweet failed to send. 

The callback should return an error at the very least so to correctly notify the user. Ideally it would bring back what the error was from Twitter.

**Comment by doefler** [comment]
Thank you for finding that and sharing it with me @dwilt 
I think it would be smart to return available error messages 👍
