### ISSUE TITLE
Unable to pic image in case of facebook 

### ISSUE THREAD

**Issue by ignivanishant** [doefler/react-native-social-share#29]
I am using **react-native-social-share**  on emulator it working fine for both twitter and Facebook ,
 but on device twitter is working fine , but i am unable to post  image on Facebook , bCoz, its unable to  select image , it not coming to dialog . Here i mentioned the code i am using.

KDSocialShare.shareOnFacebook({
        'text': "Abc",
        'link':'https://www.google.co.in/',
     'imagelink': 'http://www.w3schools.com/images/w3schools_green.jpg',
      },
      (results) => {
       
      }
    );

Thanks In Advance

**Comment by doefler** [comment]
Hi @ignivanishant 

Thank you for using my code. 👍 

I don't know for sure what is causing this.
Many people have however experienced problems with Facebook on the device.
I just did a Google search and found this:
https://developers.facebook.com/docs/apps/review/prefill

It seems like Facebook is restricting what things can be prefilled.
So I don't think it is a technical/code error, but more of a strategy from Facebook's side.

Hope you find a solution or a way to give your users a great experience anyway.

Have a great day  😄

**Comment by ignivanishant** [comment]
Thank You doefler , could you please suggest any way achieve this  bcoz , i need to share it..

**Comment by doefler** [comment]
You are welcome 👍 

I think you need to use the API for full posting permission instead:
https://developers.facebook.com/docs/graph-api/reference/v2.8/post

Then you also need to get the user permissions to post.
