### ISSUE TITLE
Predefined text not populating the Facebook share dialog?

### ISSUE THREAD

**Issue by MossP** [doefler/react-native-social-share#4]
Hi, thanks for this plugin. Just been trying it out, looks good but noticed that I cannot preset the text in the popup. It always defaults to two newlines then the URL that was passed in. Any ideas?

Also, small readme error; the parameters lists 'text' twice rather than 'imagelink' for the third parameter :)

**Comment by doefler** [comment]
Hi Moss

You are welcome and thank for taking the time to give feedback! :smile: 
I experienced the same bug with prefilled text with Facebook share, but only on the phone, not in the simulator. That made it a bit difficult for me to debug. I tried to search the web, but didn't find a solution at the time. I really want a solution,so if you have any ideas in what direction to look I will be happy to update it!

Thanks I will change the readme next time i sit with the codes :smiley:

**Comment by MossP** [comment]
It looks like a number of things that are causing this. I don't have a full solution yet but it appears that prefilling text is against Facebook's Platform Policy:
https://developers.facebook.com/policy/#control

Which means only the title can be set but SLComposeViewController has no equivalent method:
https://developer.apple.com/library/prerelease/ios/documentation/NetworkingInternet/Reference/SLComposeViewController_Class/index.html

In contrast to what you experienced, I could not get this to work in the simulator at all. I'll post an update if I find one, but I may move on to other things for now and come back to this.
