### ISSUE TITLE
KDSocialShare is not abstract and does not override abstract method createJSModules(

### ISSUE THREAD

**Issue by shikya** [doefler/react-native-social-share#53]
Followed the guidelines to readme.

```
:react-native-social-share:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/shrikantsonone/AskDOSS/doss.askdoss.homesearch.mobile/consumer_app/Homesearch/node_modules/react-native-social-share/android/src/main/java/com/barefootcoders/android/react/KDSocialShare/KDSocialShare.java:15: error: KDSocialShare is not abstract and does not override abstract method createJSModules() in ReactPackage
public class KDSocialShare implements ReactPackage {
       ^
1 error
:react-native-social-share:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-social-share:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.397 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html
```

**Comment by angusmccloud** [comment]
My guess is that this is from the Android Oreo update. I've been compiling both iOS and Android on BuddyBuild, and this week all my branches stopped compiling (on Android only, iOS is fine). To verify it wasn't something I broke, I tried re-compiling a branch that I'd made no changes to and it also broke with this error (telling me this plugin is likely not compatible with that new underlying architecture).

I have not jumped in to try and find out WHY yet, but that seems to be the overall cause from my side.

**Comment by shikya** [comment]
Could be, but I've not updated my SDK nor any packages.

**Comment by mantou132** [comment]
same problem

**Comment by bsy** [comment]
+1 anyone find a resolution

**Comment by kisubs** [comment]
I added the following code in KDSocialShare.java and it works
`
@Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
`

It's just a workaround, not a proper fix.

**Comment by kisubs** [comment]
I added the following code in KDSocialShare.java and it works
`@Override`
    `public List<Class<? extends JavaScriptModule>> createJSModules() {`
        `return Collections.emptyList();`
   ` }`


Not sure if it's a proper fix though.

**Comment by doefler** [comment]
Hi 
I merged the changes made by @bsy into the repo. Thanks 😄 
It is available with NPM 👍 

CC @kisubs
