### ISSUE TITLE
update react-native dependency for supporting 0.6-RC

### ISSUE THREAD

**Issue by chirag04** [doefler/react-native-social-share#6]
Right now the dependency of 0.4.4 creates a new react-native install inside social-share Change it to 0.5 so that it works with both 0.5 and 0.6 without install react-native again inside social-view.

https://github.com/chirag04/react-native-dashed-border/blob/master/package.json#L24-L26

Refer:
https://github.com/naoufal/react-native-activity-view/issues/3

**Comment by chirag04** [comment]
@doefler  This module is breaking the app with 0.6 which got released today. It's because of the dependency on react-native. I can PR to fix this.

Change dependecy to:
``js
"peerDependencies": {
    "react-native": ">= 0.4 || 0.7.0-rc1"
}
``

**Comment by doefler** [comment]
should i remove this line

  "dependencies": {
    "react-native": "^0.4.0"
  },

and replace it with 

"peerDependencies": {
    "react-native": ">= 0.4 || 0.7.0-rc1"
}

or have them both?

**Comment by chirag04** [comment]
yes

**Comment by doefler** [comment]
Should be updated now!?
Sorry for my confusion, have a lot of stuff going on at the moment :smile:

**Comment by chirag04** [comment]
sure no problem. Thanks for adding. Can you bump the version to npm?


Happy to help and maintain if you want me to. We are using this package in production so def want to move this package forward.

**Comment by doefler** [comment]
I just updated the version number, should be live now ;)

**Comment by doefler** [comment]
Btw, do you know any command to update all node modules at once?
In another project, I want to update my react-native module as well as all the extensions like this module.

**Comment by chirag04** [comment]
``npm update`` will update every npm module in your package.json. If you want to save the updates, ``npm udpate --save``

**Comment by doefler** [comment]
Even though I use the npm update it still keeps the same old modules
```
"dependencies": {
    "react-native": "^0.4.0",
    "react-native-facebook-login": "^0.4.6",
    "react-native-icons": "0.0.5",
    "react-native-navbar": "^0.4.6",
    "react-native-social-share": "0.0.1"
  }
```
And i get an error if i try `npm udpate --save`

**Comment by chirag04** [comment]
ohk. Change the version to ``*`` for all these and save the package.json. Run the update with save which will save the right version back into the file.
