### ISSUE TITLE
IOS always return "not_available". Working fine on android. 

### ISSUE THREAD

**Issue by decodez** [doefler/react-native-social-share#60]
When I try to share a link on IOS it always return "not_available". I thought it is because the simulator doesnt have facebook app. But i tried  on an actual device also wont open the dialogue box.

**Comment by udfalkso** [comment]
Same thing here.  v1.4.0

**Comment by udfalkso** [comment]
This seems to be related to changes in IOS 11 whereby twitter & facebook are no longer directly integrated:
https://stackoverflow.com/questions/35263309/how-to-share-content-on-facebook-twitter-and-instagram-using-slcomposeviewcontr

I managed to get somewhere for the moment by commenting out the availability check in KSSocialShare.m

<img width="637" alt="screen shot 2018-02-07 at 8 18 21 pm" src="https://user-images.githubusercontent.com/2029383/35950346-1005ca36-0c44-11e8-911a-269113ba90fb.png">

For Twitter and FB the setting of text then seems to not work, although the setting of urls does work (FB was already this way previously, but not Twitter).

**Comment by decodez** [comment]
Thanks @udfalkso That works! I only needed FB share. thanks a lot

**Comment by akiradeveloper** [comment]
This issue is annoying me now.

**Comment by Sreekanthp74** [comment]
Twitter share also not working in iOS

**Comment by udfalkso** [comment]
Apparently there's some built in sharing in RN now, using the native share sheet.  I'm moving to this for stability's sake:
https://facebook.github.io/react-native/docs/share.html

**Comment by ariiyu** [comment]
Thanks  @udfalkso, It worked for me.
Also Twitter share worked in my case.

@doefler I created fork and a pull request. https://github.com/doefler/react-native-social-share/pull/63

**Comment by doefler** [comment]
@ariiyu you are welcome
Thank you for taking the time to improve the code in #63 
Will merge and update NPM now 👍
