### ISSUE TITLE
shareOnFacebook returns error on Android

### ISSUE THREAD

**Issue by ariiyu** [doefler/react-native-social-share#67]
`shareOnFacebook` method returns "error" and fails to open Facebook app.
I ran into the problem with Android 6.0.

**Comment by ariiyu** [comment]
An exception is thrown at `reactContext.startActivity(shareIntent)`.

```java
  @ReactMethod
  public void shareOnFacebook(ReadableMap options, Callback callback) {
    try {
      Intent shareIntent;

      if (options.hasKey("text") && doesPackageExist("com.facebook.katana")) {
        String shareText = options.getString("text");
        shareIntent = new Intent(Intent.ACTION_SEND);
        shareIntent.setType("text/plain");
        shareIntent.putExtra(Intent.EXTRA_TEXT, shareText);
      } else if (options.hasKey("link")) {
        String shareUrl = options.getString("link");
        String sharerUrl = "https://www.facebook.com/sharer/sharer.php?u=" + Uri.encode(shareUrl);
        shareIntent = new Intent(Intent.ACTION_VIEW, Uri.parse(sharerUrl));
      } else {
        if (options.hasKey("text") && !doesPackageExist("com.facebook.katana")) {
          callback.invoke("error", "If text is provided to Facebook sharing, the application must be installed");
        } else {
          callback.invoke("error");
        }
        return;
      }

      reactContext.startActivity(shareIntent); // throws exception
    } catch (Exception ex) {      
      callback.invoke("error"); // returns "error" to React Native
    }
  }
```

The exception's message is `Calling startActivity() from outside of an Activity context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?`. 

```java
   } catch (Exception ex) {     
-      callback.invoke("error") 
+      callback.invoke(ex.getMessage()); 
    }
```

![ex_getmessage_resized](https://user-images.githubusercontent.com/3273978/45742891-ecfb9780-bc35-11e8-9197-9c4df4c7d28c.jpg)

**Comment by ariiyu** [comment]
@doefler Hi, I created a pull request for this issue. https://github.com/doefler/react-native-social-share/pull/68

**Comment by doefler** [comment]
Thank you @ariiyu 
I have merged it 👍

**Comment by ariiyu** [comment]
@doefler Thank you!!

I'm not an expert of Android. 
So please review and refine the code if there's a chance.

**Comment by minhtule** [comment]
I'm sorry guys. I'm not keeping up with the latest changes to be helpful here (I'm not doing mobile development at the moment 😅)

**Comment by Jberlinsky** [comment]
I'm in the same situation as @minhtule, unfortunately. Sorry!
