### ISSUE TITLE
Share functionality not working on simulator

### ISSUE THREAD

**Issue by mebinum** [doefler/react-native-social-share#7]
Hey thanks for the plugin, I just tried using it but it didn't work on the iOS Simulator (iOS 8.3) after some searching around I found this on [stackoverflow!](http://stackoverflow.com/questions/14145322/ios-6-social-framework-not-going-to-settings-or-no-alert) which suggested to comment out 

      if([SLComposeViewController isAvailableForServiceType:SLServiceTypeFacebook]) {
and

         if([SLComposeViewController isAvailableForServiceType:SLServiceTypeTwitter]) {

and that fixed it, is there something we can do to get it to work on both Simulator and device or can we just comment out those lines

**Comment by vinu123** [comment]
Same here.

**Comment by WestleyArgentum** [comment]
+1 same problem

**Comment by doefler** [comment]
This problem has been fixed by @WestleyArgentum :+1: 
I have updated NPM :smile:
