### ISSUE TITLE
shareOnFacebook returns error on Android 9.0

### ISSUE THREAD

**Issue by tamago3keran** [doefler/react-native-social-share#74]
shareOnFacebook method returns "error" and fails to open Facebook app.
I ran into the problem with Android 9.0.

An exception is thrown at `reactContext.startActivity(shareIntent)`.

https://github.com/doefler/react-native-social-share/blob/b4b51d77974652c14824daa066f017c117c4708f/android/src/main/java/com/barefootcoders/android/react/KDSocialShare/KDSocialShareModule.java#L56-L89

The exception's message is `Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?`.

```diff
  } catch (Exception ex) {
-   callback.invoke("error");
+   callback.invoke(ex.getMessage());
  }
```

<img width="1176" alt="Screen Shot 2019-08-25 at 8 04 45" src="https://user-images.githubusercontent.com/24249859/63643611-2161b880-c70f-11e9-8614-cb52c78427f2.png">

**Comment by tamago3keran** [comment]
@doefler Hi, I created a pull request for this issue. https://github.com/doefler/react-native-social-share/pull/75

I'm not an expert of Android.
So please review and refine the code of the pull request if there's a chance.

**Comment by doefler** [comment]
Hey @tamago3keran 

Thanks for reporting the bug and going through the trouble to fix it yourself. 🙏
I have merged it into the repo and will release a new NPM version.

Thanks
Kim

**Comment by tamago3keran** [comment]
Hi @doefler 

Thank you for merge this PR!

Takuma
